prestige:
  cost: 10000000000
  rewards:
  - 'console:lp user %player% group remove Z'
  - 'console:lp user %player% group add A'
  - 'console:crate give %player% Prosperous 1'
  
fortune:
  multi: 1.25
  allowed_worlds:
    - NewMines
  fortune_blocks:
    - DIAMOND_ORE
    - EMERALD_ORE
    - GOLD_ORE
    - IRON_ORE
    - LAPIS_ORE
    - REDSTONE_ORE
    - QUARTZ_ORE
    - COAL_ORE
    - DIAMOND_BLOCK
    - EMERALD_BLOCK
    - GOLD_BLOCK
    - IRON_BLOCK
    - LAPIS_BLOCK
    - REDSTONE_BLOCK
    - QUARTZ_BLOCK
    - COAL_BLOCK